"""The text layer — §24's honesty controls.

`scm.py` decides what happened and `generator.py` decides what each department
wrote down. This file decides **what the words were**, which is the half the
retrieval and extraction stages actually read.

Four controls, from §24, and each one is a rule this module obeys rather than a
claim it makes:

1. **Generate once, freeze, commit.** No live generation at demo time, so the
   model writing tickets is never the model reading them in the same run.
2. **~85% irrelevant traffic** — password resets, billing queries, feature
   requests. *Finding a needle in a stack of needles proves nothing.*
3. **Deliberately misleading documents** — a ticket that mentions the integration
   and concludes it was fine; a CRM note blaming pricing with no evidence;
   genuinely ambiguous notes.
4. **The noise is templates; the signal is authored.** The irrelevant traffic is
   template-generated from a vocabulary sampled per §21 Layer 1 — tens of
   thousands of documents that need no model. Only the few dozen that carry
   signal or misdirection are written by hand, under `data/corpus/authored/`.

**What is committed, and the one place this departs from §41.2.** §41.2 lists
`data/corpus/` as committed. The authored documents are — they are a few
kilobytes and they are the part a reviewer has to be able to read in a diff. The
~46k template documents are **regenerated byte-identically from the seed** by
`make data` instead of being carried in git, because 30-odd MB of generated prose
is exactly the dead weight §41.2's own ignore list objects to. §24's requirement
is that nothing is generated *by a model* at demo time, and templates are not a
model.
"""

from __future__ import annotations

import random
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

import yaml

AUTHORED_DIR = Path(__file__).resolve().parents[3] / "data" / "corpus" / "authored"

#: §24's ~85%. Categories a support desk fills its day with and no investigation
#: has ever turned on. The weights are what make the claim measurable.
NOISE_CATEGORIES: tuple[str, ...] = ("how_to", "billing_query", "access")
SIGNAL_CATEGORIES: tuple[str, ...] = ("integration", "performance")
CATEGORY_WEIGHTS = {
    "how_to": 0.31,
    "billing_query": 0.29,
    "access": 0.25,
    "integration": 0.09,
    "performance": 0.06,
}


class CorpusError(ValueError):
    """An authored document that does not attach to anything in the corpus."""


@dataclass(frozen=True)
class Authored:
    """One hand-written document. `front` is its YAML header verbatim."""

    doc_id: str
    table: str
    role: str
    front: dict[str, object]
    body: str

    @property
    def account(self) -> str | None:
        value = self.front.get("account")
        return str(value) if value else None

    @property
    def date(self) -> str:
        return str(self.front["date"])

    def get(self, key: str, default: str = "") -> str:
        value = self.front.get(key)
        return default if value is None else str(value)


def load_authored(directory: Path | str = AUTHORED_DIR) -> list[Authored]:
    """Every committed document, in filename order so the corpus is stable."""
    documents: list[Authored] = []
    for path in sorted(Path(directory).glob("*.md")):
        front, body = _split_front_matter(path)
        for required in ("doc_id", "table", "date", "role"):
            if required not in front:
                raise CorpusError(f"{path.name} has no {required!r} in its front matter")
        documents.append(
            Authored(
                doc_id=str(front["doc_id"]),
                table=str(front["table"]),
                role=str(front["role"]),
                front=front,
                body=body,
            )
        )

    seen = [d.doc_id for d in documents]
    if len(set(seen)) != len(seen):
        raise CorpusError(f"duplicate doc_id among authored documents: {sorted(seen)}")
    return documents


def _split_front_matter(path: Path) -> tuple[dict[str, object], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise CorpusError(f"{path.name} does not open with a YAML front-matter fence")
    _, header, body = text.split("---\n", 2)
    front = yaml.safe_load(header)
    if not isinstance(front, dict):
        raise CorpusError(f"{path.name} has a front matter that is not a mapping")
    return front, " ".join(body.split())


# ── The template vocabulary — §21 Layer 1 ────────────────────────────────────
# Shapes and phrasing sampled from the public support corpora §21 names. They are
# deliberately dull: this is the stack of needles, and every hour spent making it
# interesting makes the benchmark easier than the real thing.

_SUBJECTS = {
    "how_to": (
        "How do I export a saved view",
        "Where do scheduled reports live now",
        "Adding a second approver to a workflow",
        "Changing the default currency on a dashboard",
        "Bulk editing tags across a project",
    ),
    "billing_query": (
        "Question about this month's invoice",
        "Purchase order number missing from the invoice",
        "Invoice arrived twice",
        "VAT treatment on the annual line",
        "Requesting a copy of last quarter's statements",
    ),
    "access": (
        "Password reset not arriving",
        "SSO login loops back to the sign-in page",
        "New starter cannot see the reporting workspace",
        "Removing access for a leaver",
        "Two-factor prompt on every page load",
    ),
    "integration": (
        "Nightly export finished with missing rows",
        "Webhook retries are failing",
        "Sync ran late and the totals do not match",
        "API returning 409 on the batch endpoint",
        "Connector disconnected overnight",
    ),
    "performance": (
        "Dashboard slow to load this morning",
        "Report timing out on a large date range",
        "Search results taking several seconds",
        "Export queue backed up",
        "Page unresponsive after the last release",
    ),
}

_OPENERS = (
    "Customer got in touch to say",
    "Raised by the account's admin team:",
    "Logged from the support portal:",
    "Reported on the morning call:",
    "Came through the shared inbox:",
)

_BODIES = {
    "how_to": (
        "they cannot find the setting after the console refresh and would like a walkthrough",
        "a new member of their team needs pointing at the documentation for scheduled reports",
        "they want to know whether the change they made can be undone without support",
    ),
    "billing_query": (
        "the invoice total does not match what their purchase order was raised for",
        "they need the statement reissued with a different billing address",
        "their finance team is querying a line they do not recognise",
    ),
    "access": (
        "the reset email has not arrived after several attempts",
        "a leaver still appears in the workspace and should be removed",
        "two of their users are being asked for a second factor on every page",
    ),
    "integration": (
        "the overnight run completed but the row count is lower than they expected",
        "their reconciliation job failed on a file that arrived incomplete",
        "the connector dropped and reconnected twice during the night",
    ),
    "performance": (
        "the reporting page has been slow since yesterday afternoon",
        "an export that normally takes minutes has been queued for over an hour",
        "their analysts are seeing timeouts on wider date ranges",
    ),
}

_CLOSERS = (
    "Walked them through it on a call and they are happy.",
    "Asked for a screenshot and the exact time it happened.",
    "Passed to the platform team for a look.",
    "Resolved on the first response; no follow-up needed.",
    "Left open pending their confirmation.",
)

_NOTE_TEMPLATES = (
    "Spoke to the account today. {topic} Next step is a follow-up call.",
    "Short update: {topic} Nothing to escalate at this stage.",
    "Notes from the quarterly review. {topic} Sponsor is unchanged.",
    "Call summary. {topic} Sending the deck across this week.",
    "Left a voicemail and followed up by email. {topic}",
)

_NOTE_TOPICS = (
    "They are broadly happy with where the rollout has got to.",
    "Usage is up in two teams and flat in the third.",
    "Procurement wants the renewal paperwork a month earlier this year.",
    "Their sponsor is moving roles; introduction to the successor next month.",
    "No open commercial questions.",
    "They asked about the roadmap for the reporting module.",
    "Budget conversations start in six weeks.",
)

_NEWS_SOURCES = ("Sector Weekly", "The Enterprise Ledger", "Market Notes", "Trade Desk Daily")
_NEWS_HEADLINES = (
    "Enterprise software spend steadies after two soft quarters",
    "Buyers report longer procurement cycles across the sector",
    "Analysts expect consolidation among mid-market platforms",
    "Survey finds integration cost the top barrier to switching",
    "Regional hiring slows at the largest platform vendors",
    "Cloud migration budgets hold flat into the new financial year",
)
_NEWS_BODIES = (
    "The report draws on a survey of finance and operations leaders and finds little "
    "change quarter on quarter.",
    "Respondents cited procurement process rather than price as the main cause of delay.",
    "The piece notes that no single vendor has moved share materially in the period.",
    "Commentators expect the picture to stay broadly flat until the second half.",
)

_MESSAGE_TEMPLATES = (
    "Thanks for the detail — we can see the run in the logs and are looking now.",
    "Could you confirm the exact time it happened and which user was signed in?",
    "We have reproduced it on a test account and have passed it to engineering.",
    "This should be resolved as of this morning; could you confirm at your end?",
    "Closing this off — please reopen if it recurs.",
)


def category(rng: random.Random) -> str:
    """A ticket category, weighted so §24's 85% noise floor is a measurement."""
    keys = list(CATEGORY_WEIGHTS)
    return rng.choices(keys, [CATEGORY_WEIGHTS[k] for k in keys])[0]


def subject(rng: random.Random, kind: str) -> str:
    return rng.choice(_SUBJECTS[kind])


def ticket_body(rng: random.Random, kind: str, account_name: str) -> str:
    return (
        f"{rng.choice(_OPENERS)} {rng.choice(_BODIES[kind])}. "
        f"Account is {account_name}. {rng.choice(_CLOSERS)}"
    )


def ticket_message(rng: random.Random) -> str:
    return rng.choice(_MESSAGE_TEMPLATES)


def note_body(rng: random.Random) -> str:
    return rng.choice(_NOTE_TEMPLATES).format(topic=rng.choice(_NOTE_TOPICS))


def news(rng: random.Random) -> tuple[str, str, str]:
    """A source, a headline and a body for one ordinary industry item."""
    return (
        rng.choice(_NEWS_SOURCES),
        rng.choice(_NEWS_HEADLINES),
        rng.choice(_NEWS_BODIES),
    )


# ── Measuring the noise floor ────────────────────────────────────────────────


def is_noise(topic: str, authored_role: str | None = None) -> bool:
    """Whether a document is part of §24's irrelevant traffic.

    A document counts as *not* noise if it is one of the authored ones — signal,
    misdirection and the deliberately ambiguous alike, because all three are
    things an investigator would want to read — or if its topic maps to a driver
    the registry can test.
    """
    if authored_role is not None:
        return authored_role == "noise"
    return topic in NOISE_CATEGORIES


def noise_share(topics: Sequence[tuple[str, str | None]]) -> float:
    """The share of `(topic, authored_role)` pairs that are irrelevant traffic."""
    if not topics:
        return 0.0
    return sum(1 for topic, role in topics if is_noise(topic, role)) / len(topics)


def main() -> None:
    """`make corpus` — validate the authored documents and report the floor.

    §41.3 describes this target as needing an API key. It does not: §24's fourth
    control is that *"the noise is templates; the signal is authored"*, so the
    only model in the corpus is the one that wrote the two dozen files under
    `data/corpus/authored/` by hand, once, into git. Regenerating needs the seed
    and nothing else, which is also why CI can do it.
    """
    from collections import Counter

    documents = load_authored()
    roles = Counter(d.role for d in documents)
    tables = Counter(d.table for d in documents)

    print(f"{len(documents)} authored documents under {AUTHORED_DIR.name}/")
    for role, count in sorted(roles.items()):
        print(f"  {role:14} {count}")
    for table, count in sorted(tables.items()):
        print(f"  {table:24} {count}")
    print()
    print("template category weights (§24's ~85% noise floor):")
    noise = sum(CATEGORY_WEIGHTS[k] for k in NOISE_CATEGORIES)
    for name, weight in sorted(CATEGORY_WEIGHTS.items(), key=lambda kv: -kv[1]):
        marker = "noise " if name in NOISE_CATEGORIES else "signal"
        print(f"  {marker} {name:14} {weight:.0%}")
    print(f"  -> {noise:.0%} irrelevant traffic by construction")


if __name__ == "__main__":
    main()
